### ISSUE TITLE
Configure the package on GitHub

### ISSUE THREAD

**Issue by luisfelipesdn12** [Richienb/minecraft-path#1]
**Is your feature request related to a problem? Please describe.**
When I've seen the repository, I searched for that "Used by" section normally seen node packages on GitHub. Then I've seen that the package were not configured yet.

**Describe the solution you'd like**
It would be really useful to configure the [node package](https://www.npmjs.com/package/minecraft-path) to the GitHub repository.

**Describe alternatives you've considered**
That can be only made by the owner of the repository. Here are some references:

- [**How to publish packages to the GitHub Package Registry - DEV**](https://dev.to/jgierer12/how-to-publish-packages-to-the-github-package-repository-4bai)
- [**Publishing a package - GitHub Docs**](https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/publishing-a-package)

**Comment by Richienb** [comment]
What's the main motivation for publishing to the Github Package Registry?

**Comment by luisfelipesdn12** [comment]
It's not a big deal actually :P
But I think that the main motivation is to have access to the repositories which uses the package with a "Used by" section.

I've heard too about more integration between npm and GitHub. But you can check out more here:

[![GitHub Packages Advantages Screenshot](https://user-images.githubusercontent.com/60361387/101413317-ce3f5500-38c2-11eb-8f08-2e8812b04581.png)](https://github.com/features/packages)

- [**GitHub Packages: Your packages, at home with their code**](https://github.com/features/packages)
- [**Introducing GitHub Package Registry - The GitHub Blog**](https://github.blog/2019-05-10-introducing-github-package-registry/)
